networks:
  dockerswarm_sd_network:
    name: dockerswarm_sd_network
    external: true

volumes:
  zones:

services:
  dns_server:
    image: dockerswarm_dns_server:latest
    hostname: dns_server
    # ports:
    #   - mode: host
    #     target: 53
    #     published: 53
    #     protocol: tcp
    #   - mode: host
    #     target: 53
    #     published: 53
    #     protocol: udp
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - dockerswarm_sd_network
    volumes:
      - zones:/etc/bind/zones
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
