networks:
  dockerswarm_sd_network:
    name: dockerswarm_sd_network
    external: true

secrets:
  cluster-sync.key:
    file: secrets/cluster-sync.key
  octodns.key:
    file: secrets/octodns.key

volumes:
  zones:

services:
  dns_server:
    image: socheatsok78/dockerswarm_dns_server:latest
    hostname: dns_server
    environment:
      - CLUSTERSYNC_KEY_FILE=/run/secrets/cluster-sync.key
      - OCTODNS_KEY_FILE=/run/secrets/octodns.key
    ports:
      - mode: host
        target: 53
        published: 53
        protocol: tcp
      - mode: host
        target: 53
        published: 53
        protocol: udp
    networks:
      - dockerswarm_sd_network
    volumes:
      - zones:/etc/bind/zones
    secrets:
      - cluster-sync.key
      - octodns.key
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
